from __future__ import annotations

import argparse
import time
from pathlib import Path

import torch

from f1_recognition.io_utils import ensure_dir, save_json


def patch_ultralytics_checkpoint_saver() -> None:
    """Use direct file checkpoint saves instead of Ultralytics' BytesIO save path.

    Some PyTorch/Python 3.13 combinations can fail while serializing a checkpoint
    to an in-memory BytesIO buffer with "I/O operation on closed file". Saving to
    a temporary file and then replacing the target avoids that fragile path.
    """
    from copy import deepcopy
    from datetime import datetime

    import torch
    from ultralytics import __version__
    from ultralytics.engine import trainer as trainer_module
    from ultralytics.engine.trainer import BaseTrainer
    from ultralytics.utils import LOGGER
    from ultralytics.utils.torch_utils import unwrap_model

    def atomic_torch_save(obj: dict, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = path.with_name(f"{path.name}.tmp")
        try:
            torch.save(obj, tmp_path)
            tmp_path.replace(path)
        finally:
            try:
                tmp_path.unlink(missing_ok=True)
            except OSError:
                pass

    def save_model_direct(self) -> bool:
        ema = deepcopy(unwrap_model(self.ema.ema)).half()
        if not all(torch.isfinite(v).all() for v in ema.state_dict().values() if isinstance(v, torch.Tensor)):
            LOGGER.warning(f"Skipping checkpoint save at epoch {self.epoch}: EMA contains NaN/Inf")
            return False

        ckpt = {
            "epoch": self.epoch,
            "best_fitness": self.best_fitness,
            "model": None,
            "ema": ema,
            "updates": self.ema.updates,
            "optimizer": trainer_module.convert_optimizer_state_dict_to_fp16(deepcopy(self.optimizer.state_dict())),
            "scaler": self.scaler.state_dict(),
            "train_args": vars(self.args),
            "train_metrics": {**self.metrics, **{"fitness": self.fitness}},
            "train_results": self.read_results_csv(),
            "date": datetime.now().isoformat(),
            "version": __version__,
            "git": {
                "root": str(trainer_module.GIT.root),
                "branch": trainer_module.GIT.branch,
                "commit": trainer_module.GIT.commit,
                "origin": trainer_module.GIT.origin,
            },
            "license": "AGPL-3.0 (https://ultralytics.com/license)",
            "docs": "https://docs.ultralytics.com",
        }

        atomic_torch_save(ckpt, self.last)
        if self.best_fitness == self.fitness:
            atomic_torch_save(ckpt, self.best)
        if (self.save_period > 0) and (self.epoch % self.save_period == 0):
            atomic_torch_save(ckpt, self.wdir / f"epoch{self.epoch}.pt")
        return True

    BaseTrainer.save_model = save_model_direct


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Train a YOLO detector for F1 cars.")
    parser.add_argument("--data", required=True, type=Path, help="Path to detector data.yaml generated by prepare_dataset.py")
    parser.add_argument("--model", default="yolov8n.pt", help="YOLO checkpoint or model name")
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--imgsz", type=int, default=1280)
    parser.add_argument("--batch", type=int, default=4)
    parser.add_argument("--device", default="0" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--project", type=Path, default=Path("outputs/training/detector"))
    parser.add_argument("--name", default="f1_car_detector")
    parser.add_argument(
        "--workers",
        type=int,
        default=0,
        help="DataLoader workers. Use 0 on Windows for large imgsz/mosaic training to avoid shared-memory failures.",
    )
    parser.add_argument("--patience", type=int, default=20)
    parser.add_argument("--cache", action="store_true", help="Cache detector images in RAM for faster small-dataset training.")
    parser.add_argument(
        "--cache-mode",
        choices=("false", "ram", "disk"),
        default=None,
        help="Ultralytics cache mode. Overrides --cache when provided.",
    )
    parser.add_argument("--cos-lr", action="store_true", help="Use cosine LR scheduling in Ultralytics training.")
    parser.add_argument("--optimizer", default="auto", help="Ultralytics optimizer setting, e.g. auto, SGD, AdamW.")
    parser.add_argument("--lr0", type=float, default=None, help="Initial learning rate passed to Ultralytics.")
    parser.add_argument("--lrf", type=float, default=None, help="Final LR fraction passed to Ultralytics.")
    parser.add_argument("--warmup-epochs", type=float, default=None, help="Warmup epochs passed to Ultralytics.")
    parser.add_argument("--warmup-bias-lr", type=float, default=None, help="Warmup bias LR passed to Ultralytics.")
    parser.add_argument("--warmup-momentum", type=float, default=None, help="Warmup momentum passed to Ultralytics.")
    parser.add_argument("--mosaic", type=float, default=1.0, help="Mosaic augmentation probability.")
    parser.add_argument("--scale", type=float, default=0.5, help="Image scale augmentation amount.")
    parser.add_argument("--close-mosaic", type=int, default=10, help="Disable mosaic in the final N epochs.")
    parser.add_argument("--max-det", type=int, default=None, help="Maximum detections per image during validation.")
    parser.add_argument("--conf", type=float, default=None, help="Confidence threshold passed to Ultralytics validation.")
    parser.add_argument("--iou", type=float, default=None, help="IoU threshold passed to Ultralytics validation.")
    parser.add_argument("--compile", action="store_true", help="Use torch.compile when supported.")
    parser.add_argument("--rect", action="store_true", help="Use rectangular training batches.")
    parser.add_argument("--no-amp", action="store_true", help="Disable AMP.")
    parser.add_argument("--exist-ok", action="store_true", help="Allow writing into an existing run directory.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--resume", action="store_true", help="Resume training from the given --model checkpoint")
    parser.add_argument(
        "--oom-fallback-batch",
        type=int,
        default=0,
        help="Retry once with this batch size when CUDA runs out of memory. Use 0 to disable.",
    )
    parser.add_argument(
        "--auto-batch",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Auto-detect the largest safe batch size using a memory probe before training.",
    )
    parser.add_argument(
        "--auto-batch-min",
        type=int,
        default=1,
        help="Minimum batch size to try during auto-batch search.",
    )
    return parser


def resolve_cache_setting(cache: bool, cache_mode: str | None) -> bool | str:
    cache_setting: bool | str = cache
    if cache_mode == "ram":
        cache_setting = True
    elif cache_mode == "disk":
        cache_setting = "disk"
    elif cache_mode == "false":
        cache_setting = False
    return cache_setting


def build_train_kwargs(args: argparse.Namespace, batch: int, name: str) -> dict:
    train_kwargs = {
        "data": str(args.data.resolve()),
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": batch,
        "device": args.device,
        "project": str(args.project.resolve()),
        "name": name,
        "workers": args.workers,
        "patience": args.patience,
        "cache": resolve_cache_setting(args.cache, args.cache_mode),
        "cos_lr": args.cos_lr,
        "optimizer": args.optimizer,
        "mosaic": args.mosaic,
        "scale": args.scale,
        "close_mosaic": args.close_mosaic,
        "compile": args.compile,
        "rect": args.rect,
        "amp": not args.no_amp,
        "exist_ok": args.exist_ok,
        "seed": args.seed,
        "deterministic": False,
        "resume": args.resume,
        "verbose": True,
    }
    if args.lr0 is not None:
        train_kwargs["lr0"] = args.lr0
    if args.lrf is not None:
        train_kwargs["lrf"] = args.lrf
    if args.warmup_epochs is not None:
        train_kwargs["warmup_epochs"] = args.warmup_epochs
    if args.warmup_bias_lr is not None:
        train_kwargs["warmup_bias_lr"] = args.warmup_bias_lr
    if args.warmup_momentum is not None:
        train_kwargs["warmup_momentum"] = args.warmup_momentum
    if args.max_det is not None:
        train_kwargs["max_det"] = args.max_det
    if args.conf is not None:
        train_kwargs["conf"] = args.conf
    if args.iou is not None:
        train_kwargs["iou"] = args.iou
    return train_kwargs


def is_cuda_oom(exc: RuntimeError) -> bool:
    message = str(exc).lower()
    return "cuda" in message and "out of memory" in message


def is_cuda_device_arg(device: str) -> bool:
    normalized = str(device).strip().lower()
    return torch.cuda.is_available() and normalized not in {"cpu", "mps"}


def probe_detector_batch(
    model_path: str,
    data_yaml: str,
    imgsz: int,
    device: str,
    target_batch: int,
    min_batch: int,
    workers: int,
) -> int:
    """Binary search for max safe batch using model.val() as a memory probe.

    Returns a batch size with a 75% safety margin vs the max that fits for val,
    since training requires more memory for activations + gradients.
    """
    from ultralytics import YOLO

    def probe(batch: int) -> bool:
        try:
            probe_model = YOLO(model_path)
            probe_model.val(data=data_yaml, imgsz=imgsz, batch=batch, device=device, workers=0, verbose=False)
            torch.cuda.empty_cache()
            return True
        except RuntimeError as exc:
            torch.cuda.empty_cache()
            if "out of memory" in str(exc).lower():
                return False
            raise

    if target_batch <= min_batch:
        return target_batch

    if probe(target_batch):
        print(f"Auto-batch: target batch {target_batch} fits validation.")
        safe_batch = max(min_batch, int(target_batch * 0.75))
        print(f"Auto-batch: using safe batch {safe_batch} for training (75% of val batch).")
        return safe_batch

    print(f"Auto-batch: target batch {target_batch} OOM during validation probe, searching...")
    lo, hi = min_batch, target_batch
    best = min_batch
    while lo <= hi:
        mid = (lo + hi) // 2
        if probe(mid):
            best = mid
            lo = mid + 1
        else:
            hi = mid - 1
    safe_batch = max(min_batch, int(best * 0.75))
    print(f"Auto-batch: validation fits at batch={best}, using safe batch={safe_batch} for training.")
    return safe_batch


def write_run_summary(save_dir: Path, args: argparse.Namespace, actual_batch: int, duration_seconds: float, val_results) -> None:
    results = getattr(val_results, "results_dict", {}) or {}
    save_json(
        save_dir / "run_summary.json",
        {
            "data": str(args.data.resolve()),
            "model": args.model,
            "epochs": args.epochs,
            "imgsz": args.imgsz,
            "requested_batch": args.batch,
            "actual_batch": actual_batch,
            "device": args.device,
            "workers": args.workers,
            "cache_mode": args.cache_mode or ("ram" if args.cache else "false"),
            "optimizer": args.optimizer,
            "lr0": args.lr0,
            "lrf": args.lrf,
            "warmup_epochs": args.warmup_epochs,
            "warmup_bias_lr": args.warmup_bias_lr,
            "warmup_momentum": args.warmup_momentum,
            "mosaic": args.mosaic,
            "scale": args.scale,
            "close_mosaic": args.close_mosaic,
            "max_det": args.max_det,
            "conf": args.conf,
            "iou": args.iou,
            "amp": not args.no_amp,
            "compile": args.compile,
            "seed": args.seed,
            "auto_batch": args.auto_batch,
            "auto_batch_min": args.auto_batch_min,
            "duration_seconds": round(duration_seconds, 2),
            "metrics": results,
        },
    )


def main() -> None:
    from ultralytics import YOLO

    args = build_parser().parse_args()
    patch_ultralytics_checkpoint_saver()
    ensure_dir(args.project.resolve())
    started = time.time()
    actual_batch = args.batch
    run_name = args.name

    should_auto_batch = args.auto_batch if args.auto_batch is not None else (
        args.oom_fallback_batch > 0 and args.oom_fallback_batch < args.batch
    )
    if should_auto_batch and is_cuda_device_arg(args.device):
        detected = probe_detector_batch(
            model_path=args.model,
            data_yaml=str(args.data.resolve()),
            imgsz=args.imgsz,
            device=args.device,
            target_batch=args.batch,
            min_batch=max(1, args.auto_batch_min),
            workers=args.workers,
        )
        actual_batch = detected
        if detected < args.batch:
            run_name = f"{args.name}_b{detected}"
    elif args.oom_fallback_batch > 0 and args.oom_fallback_batch < args.batch:
        print(f"OOM fallback batch {args.oom_fallback_batch} configured (auto-batch not enabled).")

    model = YOLO(args.model)
    try:
        run = model.train(**build_train_kwargs(args, batch=actual_batch, name=run_name))
    except RuntimeError as exc:
        fallback_batch = args.oom_fallback_batch if not should_auto_batch else 0
        if not (fallback_batch > 0 and fallback_batch < actual_batch and is_cuda_oom(exc)):
            raise
        print(f"CUDA OOM with batch={actual_batch}; retrying once with batch={fallback_batch}.")
        torch.cuda.empty_cache()
        actual_batch = fallback_batch
        run_name = f"{args.name}_b{fallback_batch}"
        model = YOLO(args.model)
        run = model.train(**build_train_kwargs(args, batch=actual_batch, name=run_name))
    val_kwargs = {
        "data": str(args.data.resolve()),
        "imgsz": args.imgsz,
        "batch": actual_batch,
        "device": args.device,
    }
    if args.max_det is not None:
        val_kwargs["max_det"] = args.max_det
    if args.conf is not None:
        val_kwargs["conf"] = args.conf
    if args.iou is not None:
        val_kwargs["iou"] = args.iou
    val_results = model.val(**val_kwargs)
    write_run_summary(Path(run.save_dir), args, actual_batch, time.time() - started, val_results)
    print(f"Detector training finished. Results: {run.save_dir}")


if __name__ == "__main__":
    main()
