from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from collections.abc import Iterator

import torch
from torch import nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader

from f1_recognition.classifier import CropClassificationDataset, MultiHeadClassifier, build_transforms
from f1_recognition.io_utils import ensure_dir, load_yaml, save_json, write_csv

CLASSIFIER_HEADS = ("team", "driver", "car_model")
TARGET_KEYS = {
    "team": "team_target",
    "driver": "driver_target",
    "car_model": "car_model_target",
}
LABEL_NAME_KEYS = {
    "team": "team_names",
    "driver": "driver_names",
    "car_model": "car_model_names",
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Train the multi-head F1 classifier.")
    parser.add_argument("--manifest", required=True, type=Path, help="Classifier manifest generated by prepare_dataset.py")
    parser.add_argument("--label-maps", required=True, type=Path, help="Label maps JSON generated by prepare_dataset.py")
    parser.add_argument("--config", type=Path, default=Path("configs/project.example.yaml"), help="YAML config with training defaults")
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/training/classifier"))
    parser.add_argument("--backbone", default=None)
    parser.add_argument("--epochs", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--weight-decay", type=float, default=None)
    parser.add_argument("--image-size", type=int, default=None)
    parser.add_argument("--num-workers", type=int, default=None)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--early-stop-score", type=float, default=None)
    parser.add_argument("--early-stop-patience", type=int, default=None)
    parser.add_argument("--no-channels-last", action="store_true", help="Disable channels-last tensors on CUDA.")
    parser.add_argument(
        "--cache-mode",
        choices=("none", "ram"),
        default="none",
        help="Preload decoded classifier crops into RAM to avoid per-epoch JPEG decode.",
    )
    parser.add_argument("--compile", action="store_true", help="Compile the classifier model with torch.compile.")
    parser.add_argument(
        "--prefetch-factor",
        type=int,
        default=None,
        help="DataLoader prefetch factor when num-workers > 0.",
    )
    parser.add_argument(
        "--persistent-workers",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Keep DataLoader workers alive between epochs when num-workers > 0.",
    )
    parser.add_argument(
        "--cuda-prefetch",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Asynchronously move the next batch to CUDA while the current batch runs.",
    )
    parser.add_argument(
        "--heads",
        nargs="+",
        choices=CLASSIFIER_HEADS,
        default=None,
        help="Classifier heads to train/evaluate. Use '--heads team car_model' to skip driver training for the first pass.",
    )
    return parser


def collate(batch: list[dict]) -> dict:
    images = torch.stack([item["image"] for item in batch])
    return {
        "images": images,
        "team_target": torch.tensor([item["team_target"] for item in batch], dtype=torch.long),
        "driver_target": torch.tensor([item["driver_target"] for item in batch], dtype=torch.long),
        "car_model_target": torch.tensor([item["car_model_target"] for item in batch], dtype=torch.long),
        "rows": [item["row"] for item in batch],
    }


def evaluate(
    model: MultiHeadClassifier,
    dataloader: DataLoader,
    device: torch.device,
    label_maps: dict,
    active_heads: list[str],
    channels_last: bool,
    cuda_prefetch: bool,
) -> tuple[dict, list[dict]]:
    model.eval()
    total = 0
    correct = {head: 0 for head in active_heads}
    rows: list[dict] = []
    with torch.inference_mode():
        for batch in iterate_batches(dataloader, device=device, channels_last=channels_last, cuda_prefetch=cuda_prefetch):
            images = batch["images"]
            outputs = model(images, heads=active_heads)
            total += images.shape[0]
            predictions = {head: outputs[head].argmax(dim=1).cpu().tolist() for head in active_heads}
            targets = {head: batch[TARGET_KEYS[head]].detach().cpu().tolist() for head in active_heads}
            for head in correct:
                correct[head] += sum(int(p == t) for p, t in zip(predictions[head], targets[head], strict=True))
            for row_index, item_row in enumerate(batch["rows"]):
                eval_row = {
                    "crop_path": item_row["crop_path"],
                    "image_name": item_row["image_name"],
                    "source": item_row["source"],
                    "tcam_visible": item_row["tcam_visible"],
                }
                for head in active_heads:
                    eval_row[f"{head}_true"] = item_row[head]
                    eval_row[f"{head}_pred"] = label_maps[LABEL_NAME_KEYS[head]][predictions[head][row_index]]
                rows.append(eval_row)
    metrics = {f"{head}_accuracy": (correct[head] / total if total else 0.0) for head in correct}
    metrics["joint_accuracy"] = (
        sum(1 for row in rows if all(row[f"{head}_true"] == row[f"{head}_pred"] for head in active_heads)) / total
        if total
        else 0.0
    )
    return metrics, rows


def build_loader(
    dataset: CropClassificationDataset,
    batch_size: int,
    shuffle: bool,
    num_workers: int,
    pin_memory: bool,
    prefetch_factor: int | None,
    persistent_workers: bool,
) -> DataLoader:
    kwargs = {
        "batch_size": batch_size,
        "shuffle": shuffle,
        "num_workers": num_workers,
        "pin_memory": pin_memory,
        "collate_fn": collate,
    }
    if num_workers > 0:
        kwargs["persistent_workers"] = persistent_workers
        kwargs["prefetch_factor"] = prefetch_factor or 2
    return DataLoader(dataset, **kwargs)


def move_batch_to_device(batch: dict, device: torch.device, channels_last: bool) -> dict:
    images = batch["images"].to(device, non_blocking=True)
    if channels_last:
        images = images.contiguous(memory_format=torch.channels_last)
    return {
        "images": images,
        "team_target": batch["team_target"].to(device, non_blocking=True),
        "driver_target": batch["driver_target"].to(device, non_blocking=True),
        "car_model_target": batch["car_model_target"].to(device, non_blocking=True),
        "rows": batch["rows"],
    }


def iterate_batches(
    dataloader: DataLoader,
    device: torch.device,
    channels_last: bool,
    cuda_prefetch: bool,
) -> Iterator[dict]:
    if device.type != "cuda" or not cuda_prefetch:
        for batch in dataloader:
            yield move_batch_to_device(batch, device=device, channels_last=channels_last)
        return

    stream = torch.cuda.Stream(device=device)
    iterator = iter(dataloader)

    def preload(cpu_batch: dict) -> dict:
        with torch.cuda.stream(stream):
            return move_batch_to_device(cpu_batch, device=device, channels_last=channels_last)

    try:
        next_batch = preload(next(iterator))
    except StopIteration:
        return

    while True:
        torch.cuda.current_stream(device).wait_stream(stream)
        batch = next_batch
        for value in batch.values():
            if isinstance(value, torch.Tensor):
                value.record_stream(torch.cuda.current_stream(device))
        try:
            cpu_batch = next(iterator)
        except StopIteration:
            yield batch
            break
        next_batch = preload(cpu_batch)
        yield batch


def main() -> None:
    args = build_parser().parse_args()
    config = load_yaml(args.config)
    train_cfg = config.get("classifier", {})
    epochs = args.epochs or train_cfg.get("epochs", 20)
    batch_size = args.batch_size or train_cfg.get("batch_size", 16)
    lr = args.lr or train_cfg.get("lr", 1e-4)
    weight_decay = args.weight_decay or train_cfg.get("weight_decay", 1e-4)
    image_size = args.image_size or train_cfg.get("image_size", 384)
    backbone = args.backbone or train_cfg.get("backbone", "resnet50")
    num_workers = args.num_workers if args.num_workers is not None else int(train_cfg.get("num_workers", 4))
    if os.name == "nt" and args.cache_mode == "ram" and num_workers > 0:
        print("Using num_workers=0 because RAM crop cache is not efficient to spawn on Windows.")
        num_workers = 0
    early_stop_score = (
        args.early_stop_score
        if args.early_stop_score is not None
        else train_cfg.get("early_stop_score", None)
    )
    early_stop_patience = (
        args.early_stop_patience
        if args.early_stop_patience is not None
        else int(train_cfg.get("early_stop_patience", 0))
    )
    active_heads = list(dict.fromkeys(args.heads or train_cfg.get("heads", list(CLASSIFIER_HEADS))))

    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)
        torch.backends.cudnn.benchmark = True
        torch.set_float32_matmul_precision("high")

    with args.label_maps.open("r", encoding="utf-8") as handle:
        label_maps = json.load(handle)

    train_tfms, eval_tfms = build_transforms(image_size=image_size)
    train_dataset = CropClassificationDataset(
        args.manifest,
        split="train",
        transform=train_tfms,
        cache_mode=args.cache_mode,
    )
    val_dataset = CropClassificationDataset(
        args.manifest,
        split="val",
        transform=eval_tfms,
        cache_mode=args.cache_mode,
    )
    device = torch.device(args.device)
    pin_memory = device.type == "cuda"
    channels_last = device.type == "cuda" and not args.no_channels_last
    train_loader = build_loader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
        prefetch_factor=args.prefetch_factor,
        persistent_workers=args.persistent_workers,
    )
    val_loader = build_loader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        prefetch_factor=args.prefetch_factor,
        persistent_workers=args.persistent_workers,
    )

    model = MultiHeadClassifier(
        backbone_name=backbone,
        num_team_classes=len(label_maps["team_names"]),
        num_driver_classes=len(label_maps["driver_names"]),
        num_car_model_classes=len(label_maps["car_model_names"]),
        pretrained=True,
        dropout=float(train_cfg.get("dropout", 0.2)),
    ).to(device)
    if channels_last:
        model = model.to(memory_format=torch.channels_last)
    if args.compile:
        model = torch.compile(model)

    criterion = nn.CrossEntropyLoss()
    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = CosineAnnealingLR(optimizer, T_max=max(1, epochs))
    scaler = torch.amp.GradScaler("cuda", enabled=device.type == "cuda")

    output_dir = ensure_dir(args.output_dir.resolve())
    best_metric = -1.0
    best_epoch = 0
    target_score_epochs = 0
    history: list[dict] = []
    started = time.time()

    for epoch in range(1, epochs + 1):
        model.train()
        running_loss = 0.0
        for batch in iterate_batches(
            train_loader,
            device=device,
            channels_last=channels_last,
            cuda_prefetch=args.cuda_prefetch,
        ):
            images = batch["images"]
            targets = {
                "team": batch["team_target"],
                "driver": batch["driver_target"],
                "car_model": batch["car_model_target"],
            }
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type=device.type, enabled=device.type == "cuda"):
                outputs = model(images, heads=active_heads)
                loss = sum(criterion(outputs[head], targets[head]) for head in active_heads) / len(active_heads)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            running_loss += loss.item() * images.size(0)
        scheduler.step()

        train_loss = running_loss / len(train_dataset)
        metrics, eval_rows = evaluate(
            model,
            val_loader,
            device=device,
            label_maps=label_maps,
            active_heads=active_heads,
            channels_last=channels_last,
            cuda_prefetch=args.cuda_prefetch,
        )
        epoch_summary = {
            "epoch": epoch,
            "train_loss": train_loss,
            **metrics,
            "lr": scheduler.get_last_lr()[0],
        }
        history.append(epoch_summary)
        head_metrics = " ".join(f"{head}={metrics[f'{head}_accuracy']:.3f}" for head in active_heads)
        print(f"Epoch {epoch:03d}: loss={train_loss:.4f} {head_metrics} joint={metrics['joint_accuracy']:.3f}")

        model_score = sum(metrics[f"{head}_accuracy"] for head in active_heads) / len(active_heads)
        if model_score > best_metric:
            best_metric = model_score
            best_epoch = epoch
            checkpoint = {
                "model_state": (model._orig_mod if hasattr(model, "_orig_mod") else model).state_dict(),
                "backbone": backbone,
                "label_maps": label_maps,
                "image_size": image_size,
                "heads": active_heads,
                "metrics": metrics,
                "epoch": epoch,
                "dropout": float(train_cfg.get("dropout", 0.2)),
            }
            torch.save(checkpoint, output_dir / "best_classifier.pt")
            eval_fieldnames = ["crop_path", "image_name", "source"]
            for head in active_heads:
                eval_fieldnames.extend([f"{head}_true", f"{head}_pred"])
            eval_fieldnames.append("tcam_visible")
            write_csv(
                output_dir / "eval_classifier.csv",
                eval_rows,
                eval_fieldnames,
            )
        if early_stop_score is not None and early_stop_patience > 0:
            target_score_epochs = target_score_epochs + 1 if model_score >= early_stop_score else 0
            if target_score_epochs >= early_stop_patience:
                print(
                    f"Early stopping after {epoch} epochs: score {model_score:.3f} "
                    f"met target {early_stop_score:.3f} for {early_stop_patience} epochs."
                )
                break

    save_json(output_dir / "training_history.json", history)
    save_json(
        output_dir / "run_summary.json",
        {
            "manifest": str(args.manifest.resolve()),
            "label_maps": str(args.label_maps.resolve()),
            "epochs": epochs,
            "batch_size": batch_size,
            "lr": lr,
            "weight_decay": weight_decay,
            "image_size": image_size,
            "backbone": backbone,
            "heads": active_heads,
            "num_workers": num_workers,
            "device": str(device),
            "channels_last": channels_last,
            "cache_mode": args.cache_mode,
            "compile": args.compile,
            "cuda_prefetch": args.cuda_prefetch,
            "prefetch_factor": args.prefetch_factor or (2 if num_workers > 0 else None),
            "persistent_workers": args.persistent_workers if num_workers > 0 else False,
            "seed": args.seed,
            "best_epoch": best_epoch,
            "duration_seconds": round(time.time() - started, 2),
            "best_score": best_metric,
        },
    )
    print(f"Classifier training finished. Best checkpoint: {output_dir / 'best_classifier.pt'}")


if __name__ == "__main__":
    main()
